### PR TITLE
Main Window Modal Fix

### PR DESCRIPTION
**Pull request by xxshadowfang**
Previously When a Modal was created from the MainPageController it wouldnt lock the input of the main page. Now it does that. #185

### CODE REVIEW

**Comment by xxshadowfang** [comment]
I also have the code to do that. As it's what I originally did. Maybe we could do that but have a conformation exit dialog? I have no strong opinions on it.

**Comment by cjm721** [comment]
Do we want to allow users to open up dialogs but never do anything with them? Right now all the Add popups you can just keep opening them and then click back on the main app and they get stuck behind it.

So I am for either making them take over the page so they must be dealt with or making them always on top of the app so you can't unknowingly disregard them.

**Comment by taylerhow** [comment]
We definitely shouldn't allow them to open multiple copies of the same dialogue. However, I don't think we should disable the main window if a child dialogue is open. I vote for just closing child dialogues if the main window is closed (and not allowing multiple copies of the same dialogue), but not disabling the main window if a child is open.

**Comment by xxshadowfang** [comment]
So now
-when the main window closes all pop ups close
-All pop-ups are on the top level
-all pop-ups cant be minimized

**Comment by taylerhow** [comment]
Gonna dismiss both reviews since they are outdated

**Pull request merged**
