### PR TITLE
[LED-106] made all windows unresizable

### PR DESCRIPTION
**Pull request by LadyMopar**
Made it so that none of the windows are resizable. Now our UI won't do weird things.

### CODE REVIEW

**Comment by shellajt** [comment]
Wouldn't we rather that they resize elegantly?

**Comment by LadyMopar** [comment]
If that's what we want. I was under the impression they should stay as they are

**Comment by shellajt** [comment]
Sounds like we should talk about it then. Lets clarify during standup tomorrow?

**Comment by taylerhow** [comment]
CJ made the main page resize much more reasonable in one of his PRs, do we still want to disable resizing?

**Comment by shellajt** [comment]
Thats a good point. CJ only did the main page, so how about we remove it for that one?

**Pull request merged**
