### PR TITLE
[LED-142] Account Balances Display

### PR DESCRIPTION
**Pull request by shellajt**
## **YOU NEED A NEW DATABASE FILE**

So I added a label above the account dropdown box to display the current account's balance. If the All Accounts aggregation is selected, you'll get a net balance for all accounts. There is no support for checkpointing yet (since we have no implementaiton for it anyway), but it'll be easy to add later.

- The Label works as a custom UI element. Its a label with its own fancy-schmancy controller. 
- Added database code to support Account Balances. 
- Added account balances in the db. 
- Added tests for said db code. 
- Wired up controller to db. 
- Wired up UI to controller. 
- Changed account insertion to create an initial account balance.

### CODE REVIEW

**Comment by shellajt** [comment]
I borked the build...looking into it

**Comment by shellajt** [comment]
Build fixed!

**Comment by LadyMopar** [comment]
I feel like it would be better to put the label under the account dropdown and maybe right justify the text in it. Right now there's kind of an awkward bunch of space in that upper corner. Thoughts?

**Comment by shellajt** [comment]
I've updated it to truncate long names and add "..." to the end

**Pull request merged**
